//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoilMuseum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accrss_Mathod
    {
        public int Access_Method_ID { get; set; }
        public string Mathod_Name { get; set; }
        public string IP_Address { get; set; }
        public System.DateTime Makedate { get; set; }
        public System.TimeSpan Time { get; set; }
    }
}
