//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoilMuseum.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SoilMuseumEntities1 : DbContext
    {
        public SoilMuseumEntities1()
            : base("name=SoilMuseumEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accrss_Mathod> Accrss_Mathod { get; set; }
        public virtual DbSet<Division> Divisions { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Employee_Designation> Employee_Designation { get; set; }
        public virtual DbSet<Soil_Discription> Soil_Discription { get; set; }
        public virtual DbSet<Upozila> Upozilas { get; set; }
        public virtual DbSet<Zila> Zilas { get; set; }
        public virtual DbSet<Image_Table> Image_Table { get; set; }
    }
}
