//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoilMuseum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Upozila
    {
        public Upozila()
        {
            this.Soil_Discription = new HashSet<Soil_Discription>();
        }
    
        public int Upozila_ID { get; set; }
        public string Upozila_Name { get; set; }
        public int Zila_Id { get; set; }
    
        public virtual ICollection<Soil_Discription> Soil_Discription { get; set; }
        public virtual Zila Zila { get; set; }
    }
}
